services:
    # app:
    #     build: ../
    #     env_file:
    #         - ../.env
    #     ports:
    #         - "3000:3000"
    #     depends_on:
    #         - database
    database:
        image: "postgres:16.0-alpine3.18"
        environment:
            POSTGRES_DB: "local_db"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "local_password"
        ports:
            - "5432:5432"
